### ISSUE TITLE
Only original variant displays

### ISSUE THREAD

**Issue by dnphipps** [takahirox/glTF-Blender-IO-materials-variants#14] opened 2022-02-11 20:50 UTC
Trying to get this to work, so close.
I’ve exported gtlf file from blender with the variant add-on and loaded into three.js, using the [example](https://threejs.org/examples/#webgl_loader_gltf_variants) from three.js to select a material variant from gui.

The model loads fine with the original variant material. The gui appears with variants listed.

But changing the material on gui doesn’t change material. 
I’m exporting as gtlf-embedded from blender.

My variants load and display on this viewer:
https://modelviewer.dev/

So I think my problem is actually with the example and parser, not the exporter.

**Comment by takahirox** [comment] 2022-04-13 07:49
We have released v0.0.3. Would you try it to check if the problem is still reproducible?

**Comment by takahirox** [comment] 2022-05-16 02:27
Closing for now. Please reopen if the problem is still reproducible with the latest add-on.

**Closed as completed by takahirox** 2022-05-16 02:27 UTC
Labels: bug
