### ISSUE TITLE
Material Variants not working

### ISSUE THREAD

**Issue by jan-erik-a** [takahirox/glTF-Blender-IO-materials-variants#12] opened 2021-10-03 16:01 UTC
Hey i really appreciate your work, but i have two problems:
1. none of the declared materials from the object properties got assigned to a material slot
2. no variant is visible after export

**Comment by takahirox** [comment] 2021-11-19 08:13
Hi, thanks for the problem report.

I speculate the root issue is same as #11. Would you mind if trying the potential solutions written in https://github.com/takahirox/glTF-Blender-IO-materials-variants/issues/11#issuecomment-972424441?

**Comment by takahirox** [comment] 2022-04-13 07:48
We have released v0.0.3. Would you try it to check if the problem is still reproducible?

**Comment by takahirox** [comment] 2022-05-16 02:33
Closing for now. Please reopen if the problem is still reproducible with the latest add-on.

**Closed as completed by takahirox** 2022-05-16 02:33 UTC
Labels: bug
