### ISSUE TITLE
Not compatible with example

### ISSUE THREAD

**Issue by yunusbayraktaroglu** [takahirox/glTF-Blender-IO-materials-variants#10] opened 2021-09-01 16:50 UTC
Hi,

gltf.userData property always returns an empty object. Variants array is not as it appears in the example image. I think usage is not same with in the example below.

https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_gltf_variants.html

**Comment by takahirox** [comment] 2021-11-16 14:20
Thanks for the problem report. Would you please elaborate for me? Did you export gltf with Blender glTF-Blender-IO-materials-variants add-on and then load it with Three.js glTF loader but fail to load?

**Comment by yunusbayraktaroglu** [comment] 2021-11-16 15:46
Actually, there is no problem with exporting and loading. I think the gltf json structure has changed so the parser is not working correctly. I was able to run it correctly by editing the parser. Let me elaborate when I look at the project again.

**Comment by takahirox** [comment] 2021-11-19 08:15
There might be a chance that the root issue is #11. Would you mind if trying the potential solutions written in https://github.com/takahirox/glTF-Blender-IO-materials-variants/issues/11#issuecomment-972424441?

**Comment by MartyMcFlyJr** [comment] 2021-12-28 14:58
I can confirm that gltf.userData property is still empty. I'm using the latest Blender Daily Version (and Three.js v136) - and tried using the Stable Blender 3.0 Release (gltf-blender-io version is 1.7.33). I also don't have any issues loading the file

**Comment by takahirox** [comment] 2021-12-29 00:07
@MartyMcFlyJr

Hi, thanks for the comment. Can you check if the extensions field in your gltf file exported with the add-on looks valid?

**Comment by MartyMcFlyJr** [comment] 2021-12-30 17:30
@takahirox there's something missing:
![extensions-field](https://user-images.githubusercontent.com/6760144/147774426-40cfa1e1-171d-4eaa-941f-57e76d844085.png)

I did register the extension: `this.loader.register(parser => new GLTFMaterialsVariantsExtension(parser));`
Could draco be the problem? I need a compression because if not, my file is 280mb ...
I will check if there is anything different if I'm not using draco


Edit: I did overlook that KHR_material_variants is true

**Comment by takahirox** [comment] 2022-01-17 07:10
Thanks for sharing the info.

Can you export it as glTF, not glb, and check if "extensions" and "meshes.primitives.extensions" fields look valid like the following image?

https://user-images.githubusercontent.com/7637832/110416635-e43aee00-8048-11eb-92b5-aa74ec41f2f9.png

**Comment by MartyMcFlyJr** [comment] 2022-01-28 15:31
Sorry for the delay...
If I export it as gltf I get an weird error - my blender updated to 3.0.1:
![Bildschirmfoto vom 2022-01-28 16-24-46](https://user-images.githubusercontent.com/6760144/151574663-31a71321-7706-49ff-9fad-2b16e38e91ca.png)

But only when exported as gltf, it works as glb (Compression enabled)
I may find time on Sunday to revert back to Blender 3.0.0 and check again

**Comment by MartyMcFlyJr** [comment] 2022-01-28 15:53
I had some issues, I get errors when I export a gltf with compression enabled, If I export it without compression it's working (gltf), Parser:
![thisgltf](https://user-images.githubusercontent.com/6760144/151577381-21ccf1e5-174e-46fb-88ff-226b4dba391d.png)
the extensions field looks different.

I need to find meshes.primitives.extensions....

**Comment by dnphipps** [comment] 2022-02-12 04:09
> Actually, there is no problem with exporting and loading. I think the gltf json structure has changed so the parser is not working correctly. I was able to run it correctly by editing the parser. Let me elaborate when I look at the project again.

Can you share what you changed in the parser to get the example to work?

**Comment by yunusbayraktaroglu** [comment] 2022-02-12 09:21
Below is the material-variants-plugin.js file I edited. I also added a few features that I needed myself. I don't have time to extract please check the object path changes.

[material-variant-plugin.zip](https://github.com/takahirox/glTF-Blender-IO-materials-variants/files/8053115/material-variant-plugin.zip)

**Comment by takahirox** [comment] 2022-04-13 07:47
We have released v0.0.3. Would you try it to check if the problem is still reproducible?

**Comment by takahirox** [comment] 2022-05-16 02:34
Closing for now. Please reopen if the problem is still reproducible with the latest add-on.

**Closed as completed by takahirox** 2022-05-16 02:34 UTC
Labels: bug
