### ISSUE TITLE
Material variants do not work / gltf code not the same as shown in Documentation / Gestaltor crahes at import

### ISSUE THREAD

**Issue by LennartSolik** [takahirox/glTF-Blender-IO-materials-variants#11] opened 2021-09-07 12:09 UTC
![Blend](https://user-images.githubusercontent.com/67275838/132341649-25adab29-c2bc-43de-9f8f-5689d3a396a9.JPG)
![Blend2](https://user-images.githubusercontent.com/67275838/132341657-2a8071c0-ca3d-46c0-ab02-a0e2374e5c69.JPG)

I tried to create a Multi Material gltf and to verifiy i imported several test files to Gestaltor.
Gestaltor crashes aswell as Babylon.js 

Babylon gives this Error:
/extensions/KHR_materials_variants/variants/Red: Failed to find index (Red)

i then opened the gltf file with notepad and compared the code to the official documentation of the KHR_materials_variants extension aswell as the picture you provide in your documentation.

Notice how the Code under "extensions" is different ("extensionUsed") and there is noting declared under the KHR_materials_variants extension.
![Notepad01](https://user-images.githubusercontent.com/67275838/132341673-802fbf44-ffd1-4a78-a022-d3e204f6ae13.JPG)

![Notepad02](https://user-images.githubusercontent.com/67275838/132341759-7eda47ce-d8ca-4929-9be0-6cf5e056dce3.JPG)

is this correct to put the names instead the numbers here behind "variants"

![Notepad03](https://user-images.githubusercontent.com/67275838/132341772-82425598-124e-4000-9ead-b62ec76b9fea.JPG)

I tried to alter the file manually but had no luck.

other gltf viewers that dont support the extension can open the model.

please fix since i just cant get this to work.

regards.

**Comment by takahirox** [comment] 2021-11-17 13:58
Hi, thanks for the problem report. I can reproduce it on Blender 2.93.5. I guess gltf-Blender-IO recently changed the API and materials-variants addon is affected? I'm investigating...

**Comment by takahirox** [comment] 2021-11-17 15:38
Sounds like this change https://github.com/KhronosGroup/glTF-Blender-IO/pull/1414 can fix?

**Comment by takahirox** [comment] 2021-11-18 01:43
I confirmed that Blender 3.0 which includes KhronosGroup/glTF-Blender-IO#1414 patch seems to export the extension correctly.

So the possible solutions would be either one
1. Manually install the latest [glTF-Blender-IO](https://github.com/KhronosGroup/glTF-Blender-IO) to your Blender
2. Download and install Blender 3.0 from [the daily builds](https://builder.blender.org/download/daily/)
3. Get Blender 2.93.2 on which the add-on worked correctly from somewhere

I keep this issue opened until the new stable Blender including the patch will be released

**Comment by LorenzWieseke** [comment] 2022-03-22 14:04
For anyone having the same issue as I just change gather_gltf_hook to gather_gltf_extensions_hook

![image](https://user-images.githubusercontent.com/29607121/159499444-92281bcb-2f68-4f9f-a294-68124235736d.png)

They changed the parameters for gather_gltf_hook(self, active_scene_idx, scenes, animations, export_settings) in the gltf-Blender-IO Add-on

**Comment by takahirox** [comment] 2022-03-22 16:57
Thanks for sharing the solution. I will look into and update the code. (Of course, PR is welcome.) Sorry for slow response/progress. I have been a bit too busy to investigate the problem.

**Comment by takahirox** [comment] 2022-04-13 07:48
We have released v0.0.3. Would you try it to check if the problem is still reproducible?

**Comment by takahirox** [comment] 2022-05-16 02:33
Closing for now. Please reopen if the problem is still reproducible with the latest add-on.

**Closed as completed by takahirox** 2022-05-16 02:33 UTC
Labels: bug
